1. Import numpy as np & see the version

In [1]:
import numpy as np
print(np.__version__)

1.16.5


2. How to create a 1D array?

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

In [3]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

In [5]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?

In [6]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr[arr % 2 == 1] = 7
arr

array([0, 7, 2, 7, 4, 7, 6, 7, 8, 7])

6. How to replace items that satisfy a condition without affecting the original array?

In [7]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
out = np.where(arr%2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. How to reshape an array?

In [8]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?

In [12]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
ab = np.concatenate([a,b], axis = 0)
ab

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [17]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
ab = np.concatenate([a,b], axis = 1)
ab

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [18]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?

In [21]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [22]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])